name: Build react app

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build react app
        uses: actions/setup-node@v3
        with:
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      # - run: npm test
