name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./cra-js

      - name: Run the tests
        run: npm test
        working-directory: ./cra-js

      - name: Build
        run: npm run build
        working-directory: ./cra-js
