name: CI/CD

on:
  pull_request:

jobs:
  formatting-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./cra-js

      - name: Check formatting
        run: npm run prettier-check
        working-directory: ./cra-js

      - name: Run the tests
        run: npm test
        working-directory: ./cra-js

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
        working-directory: ./cra-js

      - name: Build
        run: npm run build
        working-directory: ./cra-js
